
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

automation:
#cloud:
config:
#counter:
frontend:
history:
#image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
#map:
#media_source:
mobile_app:
#person:
scene:
script:
#ssdp:
#sun:
system_health:
#tag:
timer:
updater:
#zeroconf:
#zone:

homeassistant:
  packages: !include_dir_named packages
python_script:

#tts:
#  - platform: google_translate

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
